services:
  - type: web
    name: msg
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run msg_app_fofinho.py --server.port $PORT --server.enableCORS false
 
